version: '3.3'
services:
  metabase:
    image: metabase/metabase:v0.40.5
    container_name: metabase
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: /run/secrets/db_user
      MB_DB_PASS: /run/secrets/db_password
      MB_DB_HOST: metabase-postgres
    networks: 
      - net-metabase
    depends_on: 
      - metabase-postgres
    secrets:
      - db_password
      - db_user
  metabase-postgres:
    image: postgres:13.4
    container_name: metabase-postgres
    hostname: metabase-postgres
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: /run/secrets/db_password
    networks: 
      - net-metabase
    secrets:
      - db_password
      - db_user
networks: 
  net-metabase:
    driver: bridge
secrets:
   db_password:
     file: db_password.txt
   db_user:
     file: db_user.txt
